[project]
name = 'stacks-pyth-network'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []

[contracts.pyth-proxy-v1]
path = 'contracts/pyth-proxy-v1.clar'
clarity_version = 2
epoch = 2.4

[contracts.pyth-oracle-v1]
path = 'contracts/pyth-oracle-v1.clar'
clarity_version = 2
epoch = 2.4

[contracts.pyth-oracle-trait]
path = 'contracts/pyth-oracle-trait.clar'
clarity_version = 2
epoch = 2.4

[contracts.wormhole-core-v1]
path = 'contracts/wormhole/wormhole-core-v1.clar'
clarity_version = 2
epoch = 2.4

[contracts.wormhole-core-trait]
path = 'contracts/wormhole/wormhole-core-trait.clar'
clarity_version = 2
epoch = 2.4

[contracts.hk-cursor-v1]
path = 'contracts/hiro-kit/hk-cursor-v1.clar'
clarity_version = 2
epoch = 2.4

[contracts.hk-merkle-tree-keccak160-v1]
path = 'contracts/hiro-kit/hk-merkle-tree-keccak160-v1.clar'
clarity_version = 2
epoch = 2.4


[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
