[project]
name = 'stacks-pyth-network'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []

[contracts.pyth-oracle-dev-preview-1]
path = 'contracts/pyth-oracle-dev-preview-1.clar'
clarity_version = 2
epoch = 2.4

[contracts.wormhole-core-dev-preview-1]
path = 'contracts/deps/wormhole-core-dev-preview-1.clar'
clarity_version = 2
epoch = 2.4

[contracts.pyth-oracle-trait]
path = 'contracts/pyth-oracle-trait.clar'
clarity_version = 2
epoch = 2.4

[contracts.wormhole-core-trait]
path = 'contracts/deps/wormhole-core-trait.clar'
clarity_version = 2
epoch = 2.4

[contracts.hk-cursor-v1]
path = 'contracts/deps/hk-cursor-v1.clar'
clarity_version = 2
epoch = 2.4

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
