[project]
name = 'stacks-pyth-network'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'SP2J933XB2CP2JQ1A4FGN8JA968BBG3NK3EKZ7Q9F.hk-cursor-v2'

[[project.requirements]]
contract_id = 'SP2J933XB2CP2JQ1A4FGN8JA968BBG3NK3EKZ7Q9F.hk-ecc-v1'

[[project.requirements]]
contract_id = 'SP2J933XB2CP2JQ1A4FGN8JA968BBG3NK3EKZ7Q9F.hk-merkle-tree-keccak160-v1'

[contracts.pyth-helper-v1]
path = 'contracts/pyth-helper-v1.clar'
clarity_version = 2
epoch = 2.4

[contracts.pyth-governance-v1]
path = 'contracts/pyth-governance-v1.clar'
clarity_version = 2
epoch = 2.4

[contracts.pyth-oracle-v2]
path = 'contracts/pyth-oracle-v2.clar'
clarity_version = 2
epoch = 2.4

[contracts.pyth-store-v1]
path = 'contracts/pyth-store-v1.clar'
clarity_version = 2
epoch = 2.4

[contracts.pyth-pnau-decoder-v1]
path = 'contracts/pyth-pnau-decoder-v1.clar'
clarity_version = 2
epoch = 2.4

[contracts.pyth-traits-v1]
path = 'contracts/pyth-traits-v1.clar'
clarity_version = 2
epoch = 2.4

[contracts.wormhole-core-v1]
path = 'contracts/wormhole/wormhole-core-v1.clar'
clarity_version = 2
epoch = 2.4

[contracts.wormhole-traits-v1]
path = 'contracts/wormhole/wormhole-traits-v1.clar'
clarity_version = 2
epoch = 2.4

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
