[project]
name = "cbtc"
authors = []
description = ""
telemetry = false

[[project.requirements]]
contract_id = "SP2J933XB2CP2JQ1A4FGN8JA968BBG3NK3EKZ7Q9F.hk-tokens-v1"

[[project.requirements]]
contract_id = "SP19F0S4GN8CJQ4K9PKWRBVE00G2C86QTPTRXZ7GP.pyth-helper-v1"

[contracts.cbtc-token]
path = "contracts/cbtc-token.clar"
clarity_version = 2
epoch = "2.4"

[contracts.cbtc-pool]
path = "contracts/cbtc-pool.clar"
clarity_version = 2
epoch = "2.4"


[repl.analysis]
passes = []
