[pyth]
network = "mainnet"
price_service_url = "https://xc-mainnet.pyth.network"
price_feeds_ids = [
    "0xec7a775f46379b5e943c3526b1c8d54cd49749176b0b98e02dde68d1bd335c17", # STX-USD (mainnet)
    "0xe62df6c8b4a85fe1a67db44dc12de5db330f7ac66b72dc658afedf0f4a415b43", # BTC-USD (mainnet)
    "0xff61491a931112ddf1bd8147cd1b641375f79f5825126d665480874634fd0ace", # ETH-USD (mainnet)
]
# Price feeds ids available here: https://pyth.network/developers/price-feed-ids

[stacks]
network = "mainnet"
stacks_node_rpc_url = "http://localhost:20443"
pyth_oracle_contract_address = "SP2J933XB2CP2JQ1A4FGN8JA968BBG3NK3EKZ7Q9F.pyth-oracle-dev-preview-1"
mnemonic = "***"
derivation_path = "m/44'/5757'/0'/0/0"
start_block = 6

[bridge]
price_updates_per_minute = 5
enable_rbf = true
enable_microbloks = true

[event_observer]
ingestion_port = 20456
bitcoind_rpc_username = "devnet"
bitcoind_rpc_password = "devnet"
bitcoind_rpc_url = "http://localhost:8332"
